### ISSUE TITLE
Right FPS lock/limit in d2fps.ini

### ISSUE THREAD

**Issue by iAskel** [Jarcho/d2dx#17] opened 2023-11-15 13:20 UTC
How exactly in the d2fps.ini file should the frame limiter be set, what does the line "This can be given as a ratio (e.g. `101/2`) or a decimal (e.g. `50.5`)" mean?
Frankly speaking it reminds of displaying fps in Minecraft through F3, I suppose I need to put 120 fps (or 116 as it is now accepted), and my monitor has a frequency of 120Hz, what to write there to limit fps was correct? Basically everything works as it is, but I want to try instead of the usual vsync (which works in conjunction with freesync of my monitor) to activate in the panel nvidia fast sync, to eliminate inputlag, well, plus achieving greater smoothness.

Yes I can use afterburner for this to limit fps, but with it occasionally there is some minilag in games and I decided not to use it for now. Thank you.

**Comment by Jarcho** [comment] 2023-11-15 20:32
It really should say "also be given as". It just means you don't have to use a whole number when filling it in.

**Comment by iAskel** [comment] 2023-11-16 09:06
Integer or fraction, as I now realize this limiter works by some logic of its own. For some reason it limits 60 frames correctly (showing me fps about 60), but instead of 120 or 119.9, which I specify the counter shows me something like 130-140. Probably the fps limiter just doesn't work as it should or once again I say, write what you need to specify for 120Hz? Or you yourself do not know how your own software works?

Translated with www.DeepL.com/Translator (free version)

**Comment by Jarcho** [comment] 2023-11-16 18:04
> Or you yourself do not know how your own software works?

Just fyi, comments like this come across as calling the other person an idiot. Unless your goal is to insult the person it doesn't add anything.

---

The limiter not working correctly was caused by a rounding error. [0.102.1](https://github.com/Jarcho/d2dx/releases/tag/v0.102.1) has a fix.

**Comment by iAskel** [comment] 2023-11-16 21:48
> > Or you yourself do not know how your own software works?
> 
> Just fyi, comments like this come across as calling the other person an idiot. Unless your goal is to insult the person it doesn't add anything.
> 
> The limiter not working correctly was caused by a rounding error. [0.102.1](https://github.com/Jarcho/d2dx/releases/tag/v0.102.1) has a fix.

No you dont idiot, but If I hadn't posted in a rude way, you never would have fixed it that way, Yes now its work properly.

**Comment by updawg** [comment] 2023-11-16 22:16
Jason,

I subscribe to your repo because of the awesome work you do and how much
you go out of your way to help anyone who has a question. I am sorry you
have to deal with ungrateful trash, but know there are others who are
supportive of your work.

**Comment by iAskel** [comment] 2023-11-16 22:53
> I subscribe to your repo because of the awesome work you do and how much you go out of your way to help anyone who has a question. I am sorry you have to deal with ungrateful trash, but know there are others who are supportive of your work.

No one asked you for your authoritative opinion, friend.

**Comment by Jarcho** [comment] 2023-11-17 02:32
> I am sorry you have to deal with ungrateful trash

As much as I appreciate the support; this part is just not needed. They're also using a translator and those are not well know for preserving meaning and writing tone very well.

**Comment by Jarcho** [comment] 2023-11-17 02:41
> For 120fps if im right correct what value should I write 119.9 instead of 120? Or 115.9 instead of 116 or im wrong? Or maybe just 120 like in RTSS limiter? Thx.

Just use the frame rate you want to set it to. No need to go slightly under. Using fractional values will only be needed for monitors that rate (some run at 59.94hz and not 60hz).

---

Since I saw the message before you started editing it,

>For some reason it limits 60 frames correctly (showing me fps about 60), but instead of 120 or 119.9, which I specify the counter shows me something like 130-140

Had this part been included in the first message I would have treated this as a bug report. The way the first message is worded it makes it seem like you just didn't understand the message in the config file.

**Comment by Jarcho** [comment] 2023-11-17 02:41
Closing since this is solved.

**Closed by Jarcho** 2023-11-17 02:41 UTC

**Comment by iAskel** [comment] 2023-11-17 08:36
> Closing since this is solved.

Yes, I use Deepl to translate as written above, and yes, I misunderstood the description in the .ini file. But I came here for support (which you say is not needed) not because I don't know English well, but because the limiter really didn't work correctly. I'm not so bad at PC that I couldn't guess to limit the framerate through one single line. So who is to blame then?
